services:
  racoder:
    image: paulgalow/racoder:latest
    container_name: racoder
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    environment:
      INPUT_STREAM: "https://as-hls-ww-live.akamaized.net/pool_26173715/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8"
      OUTPUT_PATH: "/bbc-radio-4-extra"
      BITRATE: 128k
      TZ: Europe/Berlin
      LOG_LEVEL: DEBUG
    read_only: true
    cap_drop:
      - ALL