# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

[build]
  image = "paulgalow/racoder:latest"

[deploy]
  strategy = "immediate"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [services.concurrency]
    type = "connections"
    soft_limit = 10
    hard_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = false
  [[services.http_checks]]
    interval = 30000
    grace_period = "5s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = 5000
    tls_skip_verify = false

[env]
  INPUT_STREAM = "https://as-hls-ww-live.akamaized.net/pool_26173715/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8"
  OUTPUT_PATH = "/bbc-radio-4-extra"
  BITRATE = "128k"
  TZ = "Europe/Berlin"
  LOG_LEVEL = "DEBUG"